Repository NewSainTurtle/NewSainTurtleProject, pull requests merged in 2023-02, with the labels that each got.

#3 [공통] 프로젝트 README 작성
  README.md
Labels: documentation

#8 [BE] feat: 프로젝트 생성
  newsainturtle/.gitignore
  newsainturtle/build.gradle
  newsainturtle/gradlew
  newsainturtle/gradlew.bat
  newsainturtle/settings.gradle
  newsainturtle/src/main/java/com/newsainturtle/NewsainturtleApplication.java
  newsainturtle/src/main/java/com/newsainturtle/alarm/controller/AlramController.java
  newsainturtle/src/main/java/com/newsainturtle/alarm/dto/AlarmRequest.java
  newsainturtle/src/main/java/com/newsainturtle/alarm/entity/Alarm.java
  newsainturtle/src/main/java/com/newsainturtle/alarm/exception/AlarmException.java
  newsainturtle/src/main/java/com/newsainturtle/alarm/repository/AlarmRepository.java
  newsainturtle/src/main/java/com/newsainturtle/alarm/service/AlarmService.java
  newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java
  newsainturtle/src/main/java/com/newsainturtle/auth/dto/AuthRequest.java
  newsainturtle/src/main/java/com/newsainturtle/auth/entity/Auth.java
  newsainturtle/src/main/java/com/newsainturtle/auth/exception/AuthException.java
  newsainturtle/src/main/java/com/newsainturtle/auth/repository/ScheduleRepository.java
  newsainturtle/src/main/java/com/newsainturtle/auth/service/ScheduleService.java
  newsainturtle/src/main/java/com/newsainturtle/common/config/WebConfig.java
  newsainturtle/src/main/java/com/newsainturtle/common/dto/BaseResponse.java
  newsainturtle/src/main/java/com/newsainturtle/common/exception/BadRequestException.java
  newsainturtle/src/main/java/com/newsainturtle/common/filter/JwtAuthenticationFilter.java
  newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java
  newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  newsainturtle/src/main/java/com/newsainturtle/schedule/exception/ScheduleException.java
  newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java
  newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
  newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  newsainturtle/src/main/java/com/newsainturtle/user/dto/UserRequest.java
  newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
  newsainturtle/src/main/java/com/newsainturtle/user/exception/UserException.java
  newsainturtle/src/main/java/com/newsainturtle/user/repository/UserRepository.java
  newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
Labels: backend, feature

#11 [BE] rename: 프로젝트 디렉토리 구조 수정
  BE/.idea/workspace.xml
  BE/newsainturtle/.gitignore
  BE/newsainturtle/build.gradle
  BE/newsainturtle/gradle/wrapper/gradle-wrapper.jar
  BE/newsainturtle/gradle/wrapper/gradle-wrapper.properties
  BE/newsainturtle/gradlew
  BE/newsainturtle/gradlew.bat
  BE/newsainturtle/settings.gradle
  BE/newsainturtle/src/main/java/com/newsainturtle/NewsainturtleApplication.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/controller/AlramController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/dto/AlarmRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/entity/Alarm.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/exception/AlarmException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/repository/AlarmRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/service/AlarmService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/AuthRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/entity/Auth.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/AuthException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/repository/ScheduleRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/service/ScheduleService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/WebConfig.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/dto/BaseResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/exception/BadRequestException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/filter/JwtAuthenticationFilter.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/ScheduleException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/UserRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/exception/UserException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/repository/UserRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/NewsainturtleApplicationTests.java
  newsainturtle/.idea/workspace.xml
Labels: backend, feature

#13 [BE]remove: 프로젝트 디렉토리 구조 수정
  newsainturtle/.idea/workspace.xml
Labels: backend

#15 [BE] feat: User Entity 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
Labels: backend, feature

#22 [BE] Cors 설정
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/WebConfig.java
Labels: backend, feature

#23 [BE] 친구 엔티티 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/entity/Friend.java
Labels: backend, feature

#28 [BE] Schedule Entity 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
Labels: backend, feature

#30 [BE] BaseResponse.class 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/common/dto/BaseResponse.java
Labels: backend, feature

#36 [BE] User Entity 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
Labels: backend, feature

#32 [BE] 알림 엔티티 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/controller/AlramController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/dto/AlarmRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/entity/Alarm.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/exception/AlarmException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/repository/AlarmRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/alarm/service/AlarmService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/FriendNotification.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/ScheduleNotification.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotificationException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
Labels: backend, feature

#37 [FE] 공통 컴포넌트 생성 & 컬러팔레트 수정
  FE/src/components/Button.tsx
  FE/src/components/Input.tsx
  FE/src/components/Modal.tsx
  FE/src/components/SwitchButton.tsx
  FE/src/components/css/Modal.module.css
  FE/src/styles/colorPalette.ts
Labels: frontend, feature

#43 [BE] Region Entity 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Region.java
Labels: backend, feature

#41 [BE] 이메일 중복검사 Repository, Sevice 테스트 코드 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/EmailDuplicateCheckRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/EmailDuplicateCheckResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/repository/UserRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/auth/controller/AuthControllerTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, feature

#45 [FE] 일정 생성1 - 지도 연결하기
  FE/public/index.html
  FE/src/app/store.ts
  FE/src/components/css/Modal.module.css
  FE/src/features/schedule/create/Create.tsx
  FE/src/features/schedule/create/CreateLeft.tsx
  FE/src/features/schedule/create/CreateRight.tsx
  FE/src/pages/MapPage.tsx
  FE/src/slices/mapSlice.ts
Labels: frontend, feature

#47 [BE] 사용자 검색 서비스 코드 작성
  BE/newsainturtle/build.gradle
  BE/newsainturtle/src/main/java/com/newsainturtle/common/dto/BaseResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
Labels: backend, feature, test

#49 [BE] 장소 Entity 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/BasicLocation.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/CustomLocation.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Location.java
Labels: backend, feature

#53 [FE] 메인페이지 캐러셀 생성
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/components/Header.tsx
  FE/src/features/main/Components/MainCarouselCard.tsx
  FE/src/features/main/Main.module.css
  FE/src/features/main/MainCarousel.tsx
  FE/src/features/main/MainDestinations.tsx
  FE/src/features/main/MainTravelLog.tsx
Labels: frontend, feature

#55 [FE] 로그인 페이지 컴포넌트 생성
  FE/src/App.tsx
  FE/src/components/Header.tsx
  FE/src/features/user/login/Login.module.css
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/login/LoginSocial.tsx
  FE/src/pages/LoginPage.tsx
Labels: frontend, feature, design

#59 [FE] 회원가입 페이지 컴포넌트 생성
  FE/src/App.tsx
  FE/src/components/Header.tsx
  FE/src/features/user/login/Login.module.css
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/regist/Regist.module.css
  FE/src/features/user/regist/Regist.tsx
  FE/src/pages/RegistPage.tsx
Labels: frontend, feature, design

#60 [BE] 로그인 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/AuthConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/LoginRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/LoginResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/UnauthorizedUserException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/service/AuthService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtTokenProvider.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
  BE/newsainturtle/src/test/java/com/newsainturtle/auth/service/AuthServiceTest.java
Labels: backend, feature, test

#63 [FE] 프로필 수정 페이지 컴포넌트 생성 및 배치
  FE/src/App.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.module.css
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx
Labels: frontend, feature, design

#67 [FE] 일정 생성 페이지 정보 입력 컴포넌트 생성 및 배치
  FE/package-lock.json
  FE/package.json
  FE/src/components/Modal.tsx
  FE/src/features/schedule/create/CreateInfo.module.css
  FE/src/features/schedule/create/CreateInfo.tsx
  FE/src/features/schedule/create/CreateSearch.tsx
  FE/src/features/schedule/create/info/Info.module.css
  FE/src/features/schedule/create/info/InfoCalendar.tsx
  FE/src/features/schedule/create/info/InfoDate.tsx
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoListPlace.tsx
  FE/src/features/schedule/create/info/InfoLocal.tsx
  FE/src/pages/MapPage.tsx
  FE/src/slices/mapSlice.ts
Labels: frontend, feature, design

#66 [BE] Auth 관련 코드 리팩토링
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/AuthConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/constant/AuthConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/LoginRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/entity/Auth.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/AuthException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/UnauthorizedUserException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/repository/ScheduleRepository.java
  BE/newsainturtle/src/test/java/com/newsainturtle/auth/service/AuthServiceTest.java
Labels: backend, recfactor

#70 [BE] 사용자 검색 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/common/constant/CommonConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/exception/JwtException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
Labels: backend, feature, test
