Repository NewSainTurtle/NewSainTurtleProject, pull requests merged in 2023-04, with the labels that each got.

#258 [FE] 선택 지역 영어 이름 저장 및 반영
  FE/src/features/main/MainDestinations/MainDestinationModal.tsx
  FE/src/features/schedule/create/buttons/PlaceAddModal.tsx
  FE/src/features/schedule/create/info/InfoLocal.tsx
  FE/src/features/schedule/create/info/InfoLocalSelect.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/slices/scheduleCreateSlice.ts
Labels: frontend, feature, fix, design

#263 [FE] 카카오 로그인 API 주소 변경
  FE/src/features/schedule/edit/Edit.module.css
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/login/LoginSocial.tsx
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, recfactor

#265 [FE] 실시간 알림 오류 수정
  FE/src/components/Header.tsx
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeItem.tsx
  FE/src/slices/authSlice.ts
  FE/src/slices/mainSlice.ts
Labels: frontend, feature, fix

#267 [FE] 일정 공개/비공개 오류 수정
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
Labels: frontend, fix

#270 [FE] 소켓 통신 오류 수정
  FE/src/features/user/notice/Notice.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, fix

#272 [BE] 실시간 알림 오류 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/WebSocketService.java
Labels: backend, fix

#275 [BE] 메인페이지 여행기 조회 접근 권한 변경
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/SecurityConfig.java
Labels: backend, feature

#271 [FE] 토큰 만료 시 로그인 리다이렉트 수정
  FE/src/components/Header.tsx
  FE/src/features/main/MainTravelLog/MainTravelLog.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, fix

#279 [FE] 소켓 연결 오류 수정
  FE/src/components/Header.tsx
  FE/src/components/HeaderMobile.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx
  FE/src/features/user/notice/Socket.ts
  FE/src/slices/authSlice.ts
Labels: frontend, fix

#283 [FE] 로그인 소켓 오류 수정
  FE/public/index.html
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/Socket.ts
Labels: frontend, fix

#285 [BE] 카카오 로그인 접근제어자 변경
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoMapResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoNicknameResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoTokenResponse.java
Labels: backend, recfactor

#288 [FE] 토큰 에러 시 로그아웃 & 메인페이지 리다이렉트
  FE/src/components/Header.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, fix

#289 [BE] 일정에 포함된 장소 세팅 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationSetRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationSetRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationSetResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/webDto/OpenStreetInfoResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/webDto/OpenStreetResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature, fix

#291 [FE] 마이페이지 타이틀 삭제 및 버튼 컬러 추가
  FE/src/features/user/myPage/myFriends/MyFriends.module.css
  FE/src/features/user/myPage/myFriends/MyFriends.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/features/user/myPage/mySchedule/MySchedule.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, recfactor

#294 [FE] 알림 메시지 출력 및 오류 수정
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Header.tsx
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeToast.tsx
  FE/src/features/user/notice/Socket.ts
Labels: frontend, feature, fix, design

#297 [BE] 장소리스트 설정 Dto 오타 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationSetRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#300 [FE] 새로고침 시 소켓 연결 오류 수정
  FE/src/App.tsx
  FE/src/features/user/notice/Socket.ts
Labels: frontend, fix

#303 [BE] 일정 목록 조회 API 일정에 포함된 장소 개수 추가
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java
Labels: backend

#304 [BE] 추천리스트 개수 제한
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/BasicLocationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
Labels: backend, fix

#306 [FE] 실시간 화면 렌더링 오류 수정
  FE/src/App.tsx
  FE/src/components/Header.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/myPage/myFriends/MyFriends.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsList.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/features/user/notice/NoticeItem.tsx
  FE/src/features/user/notice/NoticeToast.tsx
  FE/src/features/user/notice/Socket.ts
  FE/src/pages/MyPage.tsx
  FE/src/slices/friendSlice.ts
Labels: frontend, feature, fix

#307 [FE] 일정 장소 세팅 API 연결
  FE/src/api/Api.ts
  FE/src/components/Header.tsx
  FE/src/features/main/MainDestinations/MainDestinationsList.tsx
  FE/src/features/schedule/create/CreateButtons.tsx
  FE/src/features/schedule/create/CreateMap.tsx
  FE/src/features/schedule/create/buttons/ImageMap.tsx
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoListPlace.tsx
  FE/src/features/schedule/create/info/InfoLocalSelect.tsx
  FE/src/features/schedule/create/search/Search.module.css
  FE/src/features/schedule/create/search/SearchCardInfoModal.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/features/schedule/create/search/SearchListCard.tsx
  FE/src/pages/ScheduleCreatePage.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/scheduleCreateSlice.ts
  FE/src/slices/scheduleEditSlice.ts
Labels: frontend, feature, recfactor, design

#310 [FE] 알림 오류 수정
  FE/src/App.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/notice/NoticeToast.tsx
  FE/src/pages/LoginPage.tsx
Labels: frontend, fix, design

#311 [FE] 모바일 반응형 프로필 사진, 이름 변경
  FE/src/components/HeaderMobile.tsx
  FE/src/components/css/Header.module.css
Labels: frontend, fix

#312 [FE] 내 일정 친구 공유 API 연결
  FE/src/api/Api.ts
  FE/src/features/user/myPage/mySchedule/MySchedule.module.css
  FE/src/features/user/myPage/mySchedule/MyScheduleInviteModal.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleShareModal.tsx
Labels: frontend, feature

#315 [FE] 일정 생성 ↔ 수정 데이터 연결
  FE/src/features/schedule/edit/fullList/EditDayScheduleList.tsx
  FE/src/features/schedule/edit/fullList/EditFullScheduleList.tsx
  FE/src/features/schedule/edit/fullList/EditScheduleItem.tsx
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, feature

#318 [FE] 파비콘 변경, 메인페이지 시작하기 버튼 활성화
  FE/public/favicon.ico
  FE/src/features/main/Components/MainCarouselCard.tsx
  FE/src/features/main/Main.module.css
  FE/src/features/main/MainDestinations/MainDestinations.tsx
  FE/src/features/main/MainDestinations/MainDestinationsList.tsx
  FE/src/features/main/MainDisplay.tsx
  FE/src/pages/MainPage.tsx
Labels: frontend, feature

#322 [FE] 메인페이지 여행지 필터링, 여행기 이미지 출력
  FE/src/features/main/Components/MainCarousel.tsx
  FE/src/features/main/MainDestinations/MainDestinationsFilter.tsx
  FE/src/features/main/MainDestinations/MainDestinationsItem.tsx
  FE/src/features/main/MainDestinations/MainDestinationsList.tsx
  FE/src/features/main/MainTravelLog/MainTravelLog.tsx
  FE/src/features/main/MainTravelLog/MainTravelLogItem.tsx
  FE/src/slices/mainSlice.ts
Labels: frontend, feature

#324 [FE] 일정 공유 시 일정 목록 확인 연결
  FE/src/features/schedule/edit/fullList/EditDayScheduleList.tsx
  FE/src/features/schedule/edit/fullList/EditFullScheduleList.tsx
  FE/src/features/user/myPage/myFriends/MyFriends.module.css
  FE/src/features/user/myPage/mySchedule/MySchedule.module.css
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, feature

#317 [BE] 실시간 알림 관련 코드 리팩토링
  BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtTokenProvider.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/WebSocketService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, recfactor

#329 [BE] 일정 장소 거리 값 추가
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationSetResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#331 [FE] 일정 수정 페이지 데이터 오류 수정
  FE/src/features/schedule/edit/EditDayList.tsx
  FE/src/features/schedule/edit/EditDayScheduleList.tsx
  FE/src/features/schedule/edit/KeepScheduleItem.tsx
  FE/src/features/schedule/edit/dayList/EditDayMoveItem.tsx
  FE/src/features/schedule/edit/dayList/EditDayMoveList.tsx
  FE/src/features/schedule/edit/fullList/EditDayScheduleList.tsx
  FE/src/features/schedule/edit/fullList/EditFullScheduleList.tsx
  FE/src/features/schedule/edit/fullList/EditScheduleItem.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/scheduleEditSlice.ts
Labels: frontend, feature, fix

#333 [FE] 일정 생성 페이지 반응형 적용
  FE/src/components/Modal.tsx
  FE/src/components/css/Modal.module.css
  FE/src/features/schedule/create/Create.module.css
  FE/src/features/schedule/create/CreateInfo.tsx
  FE/src/features/schedule/create/CreateMap.tsx
  FE/src/features/schedule/create/CreateSearch.tsx
  FE/src/features/schedule/create/buttons/ImageMap.tsx
  FE/src/features/schedule/create/buttons/PlaceAddModal.tsx
  FE/src/features/schedule/create/info/Info.module.css
  FE/src/features/schedule/create/info/InfoDate.tsx
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoLocal.tsx
  FE/src/features/schedule/create/info/InfoSelectList.tsx
  FE/src/features/schedule/create/search/Search.module.css
  FE/src/features/schedule/create/search/SearchCardInfoModal.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/pages/ScheduleCreatePage.tsx
Labels: frontend, feature, design

#334 [FE] 알림 오류 및 CSS 수정
  FE/src/App.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsList.tsx
  FE/src/features/user/notice/Notice.module.css
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeItem.tsx
Labels: frontend, recfactor, fix, design

#336 [FE] 친구 검색 결과값 없을 시 화면 디자인
  FE/src/asset/turtle.svg
  FE/src/features/user/myPage/myFriends/MyFriends.module.css
  FE/src/features/user/myPage/myFriends/MyFriendsSearch.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsSearchErr.tsx
Labels: frontend, feature, design

#338 [FE] 일정 생성 페이지 코드 리팩토링 & 반응형 선택목록 모달 스크롤 적용
  FE/src/AuthRoute.tsx
  FE/src/components/Header.tsx
  FE/src/components/HeaderMobile.tsx
  FE/src/components/Input.tsx
  FE/src/features/main/MainDisplay.tsx
  FE/src/features/schedule/create/CreateInfo.tsx
  FE/src/features/schedule/create/info/Info.module.css
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoListPlace.tsx
  FE/src/features/schedule/create/info/InfoLocalSelect.tsx
  FE/src/features/schedule/create/info/InofoSelectList.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/features/schedule/create/search/SearchListCard.tsx
  FE/src/features/temp/InsertData.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, recfactor, design

#339 [FE] 지도 마커 클릭 시 장소 정보 모달창 및 마커 순서 추가
  FE/src/features/schedule/create/CreateMap.tsx
  FE/src/features/schedule/edit/EditMap.tsx
Labels: frontend, feature

#342 [BE] 일정 장소 DTO에 장소이미지 추가
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, fix

#344 [BE] 일정 수정 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#345 [FE] 일정 수정 페이지 시간 계산 오류 수정
  FE/src/features/schedule/edit/KeepScheduleItem.tsx
  FE/src/features/schedule/edit/fullList/EditScheduleItem.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
Labels: frontend, feature, fix

#346 [BE] 일정 수정 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleUpdateRequest.java
Labels: backend, feature

#348 [FE] 로딩 컴포넌트 제작 및 구현
  FE/src/components/Loding.tsx
  FE/src/components/css/Loding.module.css
  FE/src/pages/ScheduleCreatePage.tsx
Labels: frontend, feature, design

#350 [FE] 메인페이지 여행기 코드 수정
  FE/src/features/main/MainTravelLog/MainTravelLog.tsx
  FE/src/features/main/MainTravelLog/MainTravelLogItem.tsx
Labels: frontend, recfactor

#352 [FE] 일정 수정 페이지 시간 계산 오류 수정 및 전체 코드 리팩토링
  FE/src/App.tsx
  FE/src/features/schedule/edit/KeepScheduleItem.tsx
  FE/src/features/schedule/edit/dayList/EditDayMoveList.tsx
  FE/src/features/schedule/edit/fullList/EditDayScheduleList.tsx
  FE/src/features/schedule/edit/fullList/EditScheduleItem.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsList.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsSearch.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsSearchItem.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeItem.tsx
  FE/src/pages/MyPage.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/mainSlice.ts
  FE/src/slices/scheduleEditSlice.ts
Labels: frontend, feature, recfactor, fix

#353 [FE] 일정 수정 페이지 시간 계산 오류 수정 및 전체 코드 리팩토링
  FE/src/features/schedule/edit/EditMap.tsx
  FE/src/features/schedule/edit/KeepScheduleItem.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, fix

#357 [FE] 사용하지않는 페이지 삭제
  FE/src/App.tsx
  FE/src/features/temp/InsertData.tsx
  FE/src/pages/DataPage.tsx
Labels: frontend, recfactor

#359 [BE] 백엔드 코드 정리
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/UserRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/exception/UserException.java
Labels: backend

#361 [BE] 코드 리팩토링
  BE/newsainturtle/src/main/java/com/newsainturtle/common/constant/CommonConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendFollowRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendRemoveRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponseRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/LocationController.java
Labels: backend, recfactor
