Repository NewSainTurtle/NewSainTurtleProject, pull requests merged in 2023-03, with the labels that each got.

#71 [FE] 프로필 일정 페이지 컴포넌트 생성 및 배치
  FE/src/features/user/myPage/mySchedule/MySchedule.module.css
  FE/src/features/user/myPage/mySchedule/MySchedule.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
Labels: frontend, feature, design

#73 [BE] 마이페이지 조회 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/NoEmailCheckException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/UserInfoResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, feature

#76 [BE] 프로필 사진 수정/등록 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ModifyProfileRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ProfileResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, feature, test

#78 [BE] 사용자 검색 API 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/UserSearchResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
Labels: backend, feature, test

#80 [FE] 메인페이지 컴포넌트 수정 및 배치
  FE/src/features/main/Components/MainDestinationModal.tsx
  FE/src/features/main/Main.module.css
  FE/src/features/main/MainDestinationsFilter.tsx
  FE/src/features/main/MainDestinationsItem.tsx
  FE/src/features/main/MainDestinationsList.tsx
  FE/src/features/main/MainDisplay.tsx
  FE/src/styles/colorPalette.ts
Labels: frontend, feature, design

#81 [BE] 지역 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/RegionController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Region.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/DuplicateException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/NullException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/ScheduleException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/RegionRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/RegionService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/schedule/repository/RegionRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/schedule/service/RegionServiceTest.java
Labels: backend, feature

#84 [BE] ScheduleMember Entity 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java
Labels: backend, feature

#86 [BE] 친구 요청 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendFollowRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/exception/UnableToRequestFriendFollowException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
Labels: backend, feature, test

#88 [BE] 여행 이름 수정 API 테스트/프로덕션 코드 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ModifyScheduleNameRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/repository/UserRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, feature

#90 [FE] 일정 수정 페이지 컴포넌트 생성 및 배치
  FE/package.json
  FE/src/App.tsx
  FE/src/app/store.ts
  FE/src/components/Header.tsx
  FE/src/components/Text.tsx
  FE/src/components/css/Text.module.css
  FE/src/features/schedule/ScheduleRouter.tsx
  FE/src/features/schedule/edit/Edit.module.css
  FE/src/features/schedule/edit/Edit.tsx
  FE/src/features/schedule/edit/EditDayItem.tsx
  FE/src/features/schedule/edit/EditDayList.tsx
  FE/src/features/schedule/edit/EditDayScheduleList.tsx
  FE/src/features/schedule/edit/EditFullScheduleList.tsx
  FE/src/features/schedule/edit/EditScheduleItem.tsx
  FE/src/index.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/scheduleEditSlice.ts
Labels: frontend, feature, design

#89 [BE] 친구 목록 조회 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendInfoResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendListResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
Labels: backend, feature, test

#92 [FE] 일정 생성 페이지 검색 컴포넌트 생성 및 배치
  FE/src/components/Button.tsx
  FE/src/features/schedule/create/CreateInfo.module.css
  FE/src/features/schedule/create/CreateInfo.tsx
  FE/src/features/schedule/create/CreateSearch.tsx
  FE/src/features/schedule/create/info/Info.module.css
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoListPlace.tsx
  FE/src/features/schedule/create/search/Search.module.css
  FE/src/features/schedule/create/search/SearchCardInfoModal.tsx
  FE/src/features/schedule/create/search/SearchInput.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/features/schedule/create/search/SearchListCard.tsx
  FE/src/features/schedule/create/search/SearchRadioBtn.tsx
  FE/src/pages/MapPage.tsx
Labels: frontend, feature, design

#93 [FE] 알림 모달 컴포넌트 생성 및 배치
  FE/src/app/store.ts
  FE/src/components/Header.tsx
  FE/src/features/user/notice/Notice.module.css
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeItem.tsx
  FE/src/slices/noticeSlice.ts
Labels: frontend, feature, design

#98 [BE] 친구 삭제 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/constant/FriendConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/controller/FriendController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/dto/FriendRemoveRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/exception/NotFriendRelationException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/exception/UnauthorizedFriendException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
Labels: backend, feature, test

#99 [BE] 일정에포함된장소 엔티티 생성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleLocation.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java
Labels: backend, feature, recfactor

#102 [BE] 일정 목록 조회 API 테스트/프로덕션 코드 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/schedule/repository/ScheduleMemberRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, feature

#101 [FE] 로그인 및 회원가입 유효성 검사 생성
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/login/LoginSocial.tsx
  FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx
  FE/src/features/user/regist/Regist.tsx
Labels: frontend, feature

#105 [FE] 일정 생성 파일 이름 변경 및 slice 통일
  FE/package-lock.json
  FE/src/App.tsx
  FE/src/app/store.ts
  FE/src/components/Header.tsx
  FE/src/features/schedule/ScheduleRouter.tsx
  FE/src/features/schedule/create/info/InfoCalendar.tsx
  FE/src/features/schedule/create/info/InfoDate.tsx
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoListPlace.tsx
  FE/src/features/schedule/create/info/InfoLocal.tsx
  FE/src/features/schedule/create/search/SearchListCard.tsx
  FE/src/features/schedule/edit/EditFullScheduleList.tsx
  FE/src/pages/ScheduleCreatePage.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/mapSlice.ts
  FE/src/slices/scheduleCreateSlice.ts
  FE/src/styles/colorPalette.ts
Labels: frontend, recfactor

#107 [BE] 일정 공개 여부 수정 API 테스트/프로덕션 코드 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, feature

#113 [BE] 사용자가 응답한 알림 전체 삭제 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationListResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/NotificationStatus.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NoResponseNotificationException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotUserOwnNotificationException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotificationException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
Labels: backend, feature, test

#108 [BE] 여행 일정 생성 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleLocation.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/NullException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/LocationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature, recfactor

#114 [FE] 일정 생성 제어 버튼에 따른 목록 추가 기능
  FE/src/features/schedule/create/CreateInfo.tsx
  FE/src/features/schedule/create/CreateMap.tsx
  FE/src/features/schedule/create/CreateSearch.tsx
  FE/src/features/schedule/create/info/InfoCalendar.tsx
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoListPlace.tsx
  FE/src/features/schedule/create/search/Search.module.css
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/features/schedule/create/search/SearchListCard.tsx
  FE/src/pages/ScheduleCreatePage.tsx
  FE/src/slices/scheduleCreateSlice.ts
Labels: frontend, feature, recfactor

#118 [FE] 친구 검색 모달 컴포넌트 생성 및 배치
  FE/src/features/user/myPage/myFriends/MyFriends.module.css
  FE/src/features/user/myPage/myFriends/MyFriends.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsAdd.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsSearchItem.tsx
Labels: frontend, feature, design

#119 [FE] 알림 컴포넌트 디자인 수정
  FE/src/components/Button.tsx
  FE/src/features/user/notice/Notice.module.css
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeItem.tsx
  FE/src/slices/noticeSlice.ts
Labels: frontend, fix, design

#120 [FE] 일정 수정 시 일자별 장소 리스트 없을 경우 순서 변경 오류 해결
  FE/src/features/schedule/edit/EditDayScheduleList.tsx
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, fix

#125 [BE] 일정생성시 포함된 멤버추가 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/NewsainturtleApplication.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/ScheduleMember.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
Labels: backend, feature, recfactor

#128 [BE] 친구 요청 알림 생성 관련 코드 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/entity/Notification.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/service/FriendServiceTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
Labels: backend, feature, test, recfactor

#130 [FE] 공통 API 파일 생성
  FE/src/api/Api.ts
  FE/src/api/JsonAxios.ts
  FE/src/api/MultipartAxios.ts
Labels: frontend, feature

#133 [BE] 유저 및 마이페이지 API 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/UserJoinRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
Labels: backend, feature, recfactor, fix

#136 [BE] 일정 조회 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleLocationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#137 [BE] 친구 요청 알림 처리 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/constant/NotificationConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/controller/NotificationController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/NotificationResponseRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/exception/NotificationResponseBadRequestException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/friend/repository/FriendRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
Labels: backend, feature, test

#141 [BE] 메인페이지에서 일정 생성 API
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#143 [FE] axios header Authorization 오류 해결
  FE/src/api/JsonAxios.ts
  FE/src/api/MultipartAxios.ts
  FE/src/slices/authSlice.ts
Labels: frontend, fix

#144 [BE] 일정생성 1 - 일정 기본 정보 변경 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/SchedulePeriodRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleStartEndLocationRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleVehicleRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#145 [BE] 일정 초대 알림 생성 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/FriendNotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/NotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/ScheduleNotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/InviteFriendRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/UnableToRequestFriendInviteException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/notification/repository/NotificationRepositoryTest.java
Labels: backend, feature, recfactor

#147 [BE] 일정 공유 친구 목록 조회 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/FriendInfoResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/FriendListResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/UninvitedUsersException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#149 [BE] 호텔/장소 검색 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationSearchRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Location.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/LocationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#152 [FE] 마이페이지 유저 정보 API 연결
  FE/src/components/Header.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx
  FE/src/features/user/regist/Regist.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, feature

#150 [FE] 일정 생성 페이지 지도 위 컴포넌트 생성 및 기능
  FE/src/components/Toast.tsx
  FE/src/features/schedule/create/Create.module.css
  FE/src/features/schedule/create/CreateButtons.tsx
  FE/src/features/schedule/create/CreateInfo.tsx
  FE/src/features/schedule/create/CreateMap.tsx
  FE/src/features/schedule/create/CreateSearch.tsx
  FE/src/features/schedule/create/buttons/CreateScheduleModal.tsx
  FE/src/features/schedule/create/buttons/ImageMap.tsx
  FE/src/features/schedule/create/buttons/PlaceAddModal.tsx
  FE/src/features/schedule/create/info/InfoCalendar.tsx
  FE/src/features/schedule/create/info/InfoDate.tsx
  FE/src/pages/ScheduleCreatePage.tsx
Labels: frontend, feature, design

#154 [BE] 일정 초대 알림 처리 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature, recfactor

#158 [FE] 사용자 정보 로컬 자동 저장 해결 & 일정 생성 페이지 이슈 수정
  FE/src/app/store.ts
  FE/src/features/schedule/create/info/InfoCalendar.tsx
  FE/src/index.tsx
  FE/src/pages/ScheduleCreatePage.tsx
Labels: frontend, fix

#159 [BE] 메인 장소 API 컬럼 추가
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/RegionController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/RegionResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Region.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/RegionService.java
Labels: backend, feature, recfactor

#165 [FE] 알림 API 연결
  FE/src/api/Api.ts
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeItem.tsx
  FE/src/slices/noticeSlice.ts
Labels: frontend, feature

#170 [FE] 메인페이지 여행지 목록 API 연결
  FE/src/components/Header.tsx
  FE/src/features/main/Components/MainDestinationModal.tsx
  FE/src/features/main/Main.module.css
  FE/src/features/main/MainDestinationsItem.tsx
  FE/src/features/main/MainDestinationsList.tsx
  FE/src/features/main/MainFooter.tsx
  FE/src/pages/MainPage.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, feature

#171 [BE] 마이페이지 일정 목록 조회 API수정
  BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtTokenProvider.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
Labels: backend, feature

#173 [FE] 친구 API 연결 오류 해결
  FE/src/features/user/myPage/myFriends/MyFriends.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/slices/friendSlice.ts
Labels: frontend, feature, fix

#178 [BE] DokcerFile 생성
  BE/newsainturtle/DockerFile
  FE/DockerFile
Labels: backend, frontend, feature

#182 [BE] 메인페이지 지역 목록 조회 api 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/SecurityConfig.java
Labels: backend, feature

#185 [FE] 실시간 알림 기능 구현
  FE/package-lock.json
  FE/package.json
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/notice/Notice.tsx
Labels: frontend, feature

#186 [BE] 실시간 알림 기능 구현
  BE/newsainturtle/build.gradle
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/SecurityConfig.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/ServerEndpointConfig.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/WebSocketConfig.java
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/service/FriendService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/dto/LiveNotificationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/NotificationService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/service/WebSocketService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/notification/service/NotificationServiceTest.java
Labels: backend, feature, recfactor

#184 [BE] 일정 생성 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature, fix

#187 [BE] 일정 삭제 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/exception/NotHostException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
Labels: backend, feature

#192 [BE] 일정 정보 수정 시 호스트만 가능하도록 변경
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleMemberRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, feature

#195 [BE] 일정 생성시 멤버 추가 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, fix

#196 [BE] 일정 삭제 시 관련 일정초대 알림 삭제
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/ScheduleNotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
Labels: backend, feature

#197 [BE] 토큰 유효성 검사 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/constant/AuthConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/TokenCheckRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/TokenCheckResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/InvalidTokenException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/service/AuthService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtAuthenticationFilter.java
  BE/newsainturtle/src/main/java/com/newsainturtle/common/security/JwtTokenProvider.java
Labels: backend, feature, recfactor

#198 [BE] 회원 탈퇴 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/friend/repository/FriendRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/notification/repository/FriendNotificationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/constant/UserConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/controller/UserController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/service/UserService.java
Labels: backend, feature

#199 [BE] 장소 검색 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/LocationController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/BasicLocationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/CustomLocationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
Labels: backend, recfactor, fix

#201 [BE] 장소 상세 조회 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleErrorConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/LocationController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/exception/NotFoundException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
Labels: backend, feature

#203 [BE] 카카오 로그인 API 작성
  BE/newsainturtle/build.gradle
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/constant/AuthConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/controller/AuthController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/KakaoCodeUrlResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoMapResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoInfoResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoNicknameResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/dto/kakao/KakaoTokenResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/KakaoLoginException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/exception/UnavailableEmailException.java
  BE/newsainturtle/src/main/java/com/newsainturtle/auth/service/AuthService.java
Labels: backend, feature

#207 [FE] 일정 생성 페이지 API 연결
  FE/src/api/Api.ts
  FE/src/asset/defaultPhoto.jpg
  FE/src/asset/markerHotel.png
  FE/src/asset/markerPlace.png
  FE/src/asset/markerPoint.png
  FE/src/features/schedule/create/Create.module.css
  FE/src/features/schedule/create/CreateMap.tsx
  FE/src/features/schedule/create/CreateSearch.tsx
  FE/src/features/schedule/create/buttons/PlaceAddModal.tsx
  FE/src/features/schedule/create/info/InfoListHotel.tsx
  FE/src/features/schedule/create/info/InfoListPlace.tsx
  FE/src/features/schedule/create/search/Search.module.css
  FE/src/features/schedule/create/search/SearchCardInfoModal.tsx
  FE/src/features/schedule/create/search/SearchInput.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/features/schedule/create/search/SearchListCard.tsx
  FE/src/features/schedule/create/search/SearchRadioBtn.tsx
  FE/src/index.css
  FE/src/slices/scheduleCreateSlice.ts
Labels: frontend, feature, recfactor, design

#209 [FE] 일정 수정 페이지로 데이터 연동
  FE/src/features/schedule/edit/Edit.module.css
  FE/src/features/schedule/edit/EditDayScheduleList.tsx
  FE/src/features/schedule/edit/EditFullScheduleList.tsx
  FE/src/features/schedule/edit/EditScheduleItem.tsx
  FE/src/pages/ScheduleCreatePage.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/scheduleCreateSlice.ts
  FE/src/slices/scheduleEditSlice.ts
Labels: frontend, feature

#211 [FE] 카카오 로그인 API 연결
  FE/src/api/Api.ts
  FE/src/api/JsonAxios.ts
  FE/src/app/store.ts
  FE/src/components/Loading.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/login/LoginSocial.tsx
  FE/src/index.tsx
Labels: frontend, feature

#214 [FE] 실시간 화면 렌더링 오류 수정
  FE/src/app/store.ts
  FE/src/features/user/myPage/myFriends/MyFriends.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsList.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsSearch.tsx
  FE/src/features/user/myPage/myFriends/MyFriendsSearchItem.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/features/user/notice/Notice.tsx
  FE/src/features/user/notice/NoticeItem.tsx
  FE/src/pages/MyPage.tsx
  FE/src/slices/friendSlice.ts
  FE/src/slices/noticeSlice.ts
Labels: frontend, fix

#212 [FE] 최종 일정 생성 API 연결
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, feature

#216 [FE] 마이페이지 일정 조회 API 연결
  FE/src/api/JsonAxios.ts
  FE/src/components/Header.tsx
  FE/src/features/user/myPage/mySchedule/MySchedule.module.css
  FE/src/features/user/myPage/mySchedule/MySchedule.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
Labels: frontend, feature

#219 [BE] 일정 조회시 지역 정보 추가 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/RegionController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/ScheduleResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Schedule.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/RegionService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
  BE/newsainturtle/src/main/java/com/newsainturtle/user/dto/ScheduleListResponse.java
  BE/newsainturtle/src/test/java/com/newsainturtle/schedule/repository/ScheduleMemberRepositoryTest.java
  BE/newsainturtle/src/test/java/com/newsainturtle/user/service/UserServiceTest.java
Labels: backend, recfactor, fix

#221 [FE] 회원탈퇴 API 연결
  FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, feature

#223 [BE] Location 장소 컬럼 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/BasicLocationRequest.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/dto/LocationResponse.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/entity/Location.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
Labels: backend, recfactor, fix

#225 [BE] Front nginx.conf 파일 추가
  FE/nginx.conf
Labels: frontend, feature

#228 [FE] 마이페이지 일정 조회 시 지역 정보 연동 수정
  FE/src/api/Api.ts
  FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
Labels: frontend, fix

#230 [FE] redux region id 추가 & 사용 코드 수정 & xsel 설치
  FE/package-lock.json
  FE/package.json
  FE/src/components/Button.tsx
  FE/src/features/main/Components/MainDestinationModal.tsx
  FE/src/features/main/MainDestinationsList.tsx
  FE/src/features/schedule/create/CreateMap.tsx
  FE/src/features/schedule/create/buttons/PlaceAddModal.tsx
  FE/src/features/schedule/create/info/InfoLocal.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
  FE/src/features/schedule/edit/EditFullScheduleList.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/scheduleCreateSlice.ts
Labels: frontend, feature, fix, design

#232 [FE] Location 관련 데이터 삽입을 위한 임시 코드 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/common/config/SecurityConfig.java
  FE/src/App.tsx
  FE/src/features/temp/InsertData.tsx
  FE/src/pages/DataPage.tsx
Labels: backend, frontend, feature

#233 [FE] 일정생성 redux 데이터 추가 & 비회원 페이지 이동 제한
  FE/src/App.tsx
  FE/src/AuthRoute.tsx
  FE/src/components/Header.tsx
  FE/src/components/css/Header.module.css
  FE/src/features/schedule/create/CreateButtons.tsx
  FE/src/pages/NotFound.tsx
  FE/src/pages/ScheduleCreatePage.tsx
  FE/src/pages/ScheduleEditPage.tsx
  FE/src/slices/scheduleCreateSlice.ts
Labels: frontend, feature, design

#238 [BE] User Entity 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/user/entity/User.java
Labels: backend, feature, fix

#239 [BE] 장소 검색 API 포함단어 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/BasicLocationRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/CustomLocationRepository.java
Labels: backend, recfactor

#243 [FE] 일정 수정 페이지 내 장소 검색, 장소 추가 버튼 및 기능 추가
  FE/src/features/schedule/create/search/SearchListCard.tsx
  FE/src/features/schedule/edit/Edit.module.css
  FE/src/features/schedule/edit/search/SearchList.tsx
  FE/src/pages/ScheduleEditPage.tsx
Labels: frontend, feature, design

#245 [BE] 여행기 조회 API 작성
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/constant/ScheduleSuccessConstant.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/controller/ScheduleController.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/repository/ScheduleRepository.java
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/ScheduleService.java
Labels: backend, feature

#248 [BE] 사용자 장소 검색 API 수정
  BE/newsainturtle/src/main/java/com/newsainturtle/schedule/service/LocationService.java
Labels: backend, fix

#249 [FE] 일정 생성 후 장소 변경 컴포넌트 수정 & 장소 상세 조회 내용 추가
  FE/src/api/Api.ts
  FE/src/features/main/Components/MainDestinationModal.tsx
  FE/src/features/schedule/create/info/InfoLocal.tsx
  FE/src/features/schedule/create/info/InfoLocalSelect.tsx
  FE/src/features/schedule/create/search/SearchCardInfoModal.tsx
  FE/src/features/schedule/create/search/SearchList.tsx
Labels: frontend, feature, recfactor, design

#250 [FE] 유저 프로필 사진 등록 및 변경 API 연결
  FE/package.json
  FE/src/api/firebaseConfig.ts
  FE/src/components/Header.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.module.css
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/features/user/myPage/myProfile/MyProfileEdit.tsx
  FE/src/slices/authSlice.ts
Labels: frontend, feature

#253 [FE] 사용자 장소 담은 리스트 제한하기
  FE/package-lock.json
  FE/src/features/schedule/create/CreateButtons.tsx
  FE/src/pages/ScheduleCreatePage.tsx
Labels: frontend, feature, design

#255 [FE] 로그인 관련 이슈 수정 & 여행기 모달창 생성
  FE/src/components/Header.tsx
  FE/src/features/main/Components/MainCarousel.tsx
  FE/src/features/main/Components/MainCarouselCard.tsx
  FE/src/features/main/Main.module.css
  FE/src/features/main/MainDestinations/MainDestinationModal.tsx
  FE/src/features/main/MainDestinations/MainDestinations.tsx
  FE/src/features/main/MainDestinations/MainDestinationsFilter.tsx
  FE/src/features/main/MainDestinations/MainDestinationsItem.tsx
  FE/src/features/main/MainDestinations/MainDestinationsList.tsx
  FE/src/features/main/MainTravelLog/MainTravelLog.tsx
  FE/src/features/main/MainTravelLog/MainTravelLogItem.tsx
  FE/src/features/main/MainTravelLog/MainTravelLogModal.tsx
  FE/src/features/user/login/Login.tsx
  FE/src/features/user/myPage/mySchedule/MySchedule.module.css
  FE/src/features/user/myPage/mySchedule/MyScheduleListItem.tsx
  FE/src/pages/MainPage.tsx
Labels: frontend, fix

#259 [FE] 여행기 API 연결 및 모달 생성, 수정
  FE/src/features/main/Components/MainCarousel.tsx
  FE/src/features/main/Components/MainCarouselCard.tsx
  FE/src/features/main/Main.module.css
  FE/src/features/main/MainDestinations/MainDestinationsItem.tsx
  FE/src/features/main/MainTravelLog/MainTravelLog.tsx
  FE/src/features/main/MainTravelLog/MainTravelLogItem.tsx
  FE/src/features/main/MainTravelLog/MainTravelLogModal.tsx
  FE/src/features/user/myPage/myProfile/MyProfile.tsx
  FE/src/features/user/myPage/mySchedule/MyScheduleList.tsx
  FE/src/pages/MyPage.tsx
  FE/src/slices/mainSlice.ts
Labels: frontend, feature
